name: My workflow
on: [push, workflow_dispatch]
jobs:
  job:
    name: My Job
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Bun
        run: bunx systeminformation
