name: My workflow
on: [push, workflow_dispatch]
jobs:
  job:
    name: My Job
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest

      - name: Bun
        run: bunx systeminformation
